import test from 'node:test';
import assert from 'node:assert/strict';
import worker from '../src/worker.js';
import {TestBucket} from './bucket.mjs';
globalThis.ASSETS={'/index.html':{encoding:'utf8',body:'<!doctype html><title>拾忆</title>',type:'text/html; charset=utf-8'}};
function request(path,{uid='alice',method='GET',body,origin='https://test.invalid'}={}){const headers={};if(uid)headers['oai-authenticated-user-id']=uid;if(method!=='GET')headers.origin=origin;if(body&&!(body instanceof FormData))headers['content-type']='application/json';return new Request('https://test.invalid/api/'+path,{method,headers,body:body instanceof FormData?body:body?JSON.stringify(body):undefined});}
const env=()=>({BUCKET:new TestBucket()});
async function save(e,text='日语学习的备注'){const f=new FormData();f.set('text',text);const res=await worker.fetch(request('memories',{method:'POST',body:f}),e);assert.equal(res.status,201);return res.json();}
test('public demo shell is available while private APIs still require login',async()=>{const e=env();const page=await worker.fetch(new Request('https://test.invalid/'),e);assert.equal(page.status,200);assert.match(await page.text(),/拾忆/);assert.equal((await worker.fetch(request('me',{uid:null}),e)).status,401)});
test('requires authenticated identity and rejects cross-origin writes',async()=>{const e=env();assert.equal((await worker.fetch(request('memories',{uid:null}),e)).status,401);assert.equal((await worker.fetch(request('memories',{method:'POST',origin:'https://evil.invalid'}),e)).status,403)});
test('records survive a new handler and are isolated by owner',async()=>{const e=env(),r=await save(e);const a=await(await worker.fetch(request('memories'),e)).json();assert.equal(a.items[0].id,r.id);const b=await(await worker.fetch(request('memories',{uid:'bob'}),e)).json();assert.equal(b.items.length,0);assert.equal((await worker.fetch(request('memories/'+r.id,{uid:'bob',method:'PATCH',body:{title:'changed'}}),e)).status,404)});
test('link and extraction-code note survive without opening target',async()=>{const e=env(),r=await save(e,'网盘 https://example.com/share?a=1\n提取码 1234');assert.deepEqual(r.links,['https://example.com/share?a=1']);assert.match(r.text,/1234/);assert.equal(r.kind,'link')});
test('trash retains content and supports restoration',async()=>{const e=env(),r=await save(e);let res=await worker.fetch(request('memories/'+r.id,{method:'PATCH',body:{deleted:true}}),e);assert.ok((await res.json()).deletedAt);res=await worker.fetch(request('memories/'+r.id,{method:'PATCH',body:{deleted:false}}),e);assert.equal((await res.json()).deletedAt,null)});
test('unconfigured AI fails explicitly and leaves source untouched',async()=>{const e=env(),r=await save(e);const res=await worker.fetch(request('memories/'+r.id+'/analyze',{method:'POST'}),e);assert.equal(res.status,503);const list=await(await worker.fetch(request('memories'),e)).json();assert.equal(list.items[0].text,r.text);assert.equal(list.items[0].summary,'')});
test('image title is based on user context, not filename; file isolation and deletion apply',async()=>{const e=env(),bytes=new Uint8Array([137,80,78,71]),f=new FormData();f.set('file',new File([bytes],'微信图片123.png',{type:'image/png'}));f.set('place','大理洱海');f.set('intent','想做');f.set('clue','湖边 同款照片');f.set('source','小红书');f.set('photoPlan','傍晚去复刻构图');const res=await worker.fetch(request('memories',{method:'POST',body:f}),e);assert.equal(res.status,201);const r=await res.json();assert.equal(r.title,'大理洱海 · 风景复刻');assert.equal(r.intent,'想做');assert.equal(r.clue,'湖边 同款照片');assert.equal(r.source,'小红书');assert.equal(r.photoPlan,'傍晚去复刻构图');const original=await worker.fetch(request('memories/'+r.id+'/file'),e);assert.equal(original.status,200);assert.equal(original.headers.get('content-type'),'image/png');assert.deepEqual(new Uint8Array(await original.arrayBuffer()),bytes);assert.equal((await worker.fetch(request('memories/'+r.id+'/file',{uid:'bob'}),e)).status,404);await worker.fetch(request('memories/'+r.id,{method:'PATCH',body:{deleted:true}}),e);assert.equal((await worker.fetch(request('memories/'+r.id+'/file'),e)).status,404)});
test('invalid intent and malicious ownership fields cannot alter owner',async()=>{const e=env(),r=await save(e);const res=await worker.fetch(request('memories/'+r.id,{method:'PATCH',body:{intent:'auto execute',id:'evil',owner:'bob',title:'新标题'}}),e);const updated=await res.json();assert.equal(updated.intent,'留作参考');assert.equal(updated.id,r.id);assert.equal(updated.title,'新标题')});
test('context fields can be edited and AI search endpoint is absent',async()=>{const e=env(),r=await save(e);const res=await worker.fetch(request('memories/'+r.id,{method:'PATCH',body:{clue:'口诀',source:'小红书',place:'教室',photoPlan:'下周复习',lifeStatus:'已完成'}}),e);const updated=await res.json();assert.equal(updated.clue,'口诀');assert.equal(updated.lifeStatus,'已完成');assert.equal((await worker.fetch(request('ask',{method:'POST',body:{query:'日语'}}),e)).status,404)});
test('reminder lifecycle retains date, allows pause and completion',async()=>{const e=env(),r=await save(e);for(const status of ['进行中','已暂停','已完成']){const res=await worker.fetch(request('memories/'+r.id,{method:'PATCH',body:{reminder:{when:'2027-01-01T09:00',priority:'重要',frequency:'每周',status}}}),e);assert.equal((await res.json()).reminder.status,status)}});
test('custom reason and flexible recurring reminder survive storage',async()=>{const e=env(),f=new FormData();f.set('text','电子书备用，以防手机里的版本找不到');f.set('intent','备用');f.set('intentDetail','电子书长期备用');f.set('source','社交媒体 / B站');f.set('reminder',JSON.stringify({when:'2027-01-02T09:00',priority:'重要',frequency:'每 5 天',mode:'interval',intervalDays:5,status:'进行中'}));const res=await worker.fetch(request('memories',{method:'POST',body:f}),e);assert.equal(res.status,201);const r=await res.json();assert.equal(r.intentDetail,'电子书长期备用');assert.equal(r.topic,'重要资料');assert.equal(r.reminder.mode,'interval');assert.equal(r.reminder.intervalDays,5)});
