const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const intents=['想买','想学','想做','想试试','留作参考','只是好笑','重要凭证','只收藏','稍后看或试','学习','待行动'];
const visibleIntents=['想买','想学','想做','想试试','留作参考','只是好笑','重要凭证'];
const actionable=new Set(['想买','想学','想做','想试试','待行动','学习','稍后看或试']);
const icons={text:'≡',link:'↗',image:'▧',audio:'♪'};
const types={text:'文字',link:'链接',image:'图片',audio:'录音'};
let records=[],me=null,mode='text',selectedIntent='留作参考',attachment=null,attachmentURL=null,view='library',filter='全部',panelQuery='',recorder=null,stream=null,recordTimer=null,recordClock=null,saving=false;

const demo=[
  {id:'demo-scenic',kind:'image',title:'大理洱海旁的观景位',text:'这个地方在大理洱海附近。我喜欢前景栏杆、湖面和远山的层次，下次傍晚去时想复刻相似构图。',summary:'画面由木质栏杆、平静湖面和远山组成，适合在日落前从观景台拍摄。',scene:'湖泊、山脉、树林与木质观景栏杆，画面有清楚的前中后景。',photoTips:'傍晚提前到达；使用横向构图；让栏杆保留在画面下方作为前景，人可站在栏杆转角附近。',topic:'旅行计划',intent:'想做',source:'小红书',clue:'大理 风景 湖边 同款照片',place:'大理洱海附近',photoPlan:'傍晚去，保留栏杆前景，拍湖面与远山的同款层次。',revisit:'下周',tags:['旅行','风景复刻'],status:'识别示例',createdAt:'2026-09-14',demo:true,demoImage:'/assets/demo-scenic-recreation.jpg'},
  {id:'demo-song',kind:'image',title:'直播弹幕里推荐的几首歌',text:'当时在直播间看到弹幕推荐，先记下歌名，晚上戴耳机听。',summary:'保存的是直播弹幕中的歌单线索。',topic:'音乐清单',intent:'想试试',source:'直播',clue:'直播 弹幕 歌名 好听',place:'',photoPlan:'',revisit:'今晚',tags:['音乐','歌单'],status:'演示',createdAt:'2026-09-13',demo:true},
  {id:'demo-japanese',kind:'image',title:'日语成对自他动词口诀',text:'最近在学日语，想把这组成对动词做成复习卡。',summary:'不是普通收藏，而是一条等待复习的学习记忆。',topic:'日语学习',intent:'想学',source:'小红书',clue:'日语 自他动词 口诀',place:'',photoPlan:'',revisit:'三天后',tags:['日语','自他动词'],status:'演示',createdAt:'2026-09-12',demo:true}
];

function notify(text){$('toast').textContent=text;$('toast').style.display='block';clearTimeout(window.toasting);window.toasting=setTimeout(()=>$('toast').style.display='none',3600)}
function show(id){if(!$(id).open)$(id).showModal()}
async function api(path,options={}){const res=await fetch('/api/'+path,options);let data;try{data=await res.json()}catch{throw new Error('服务暂时不可用，请稍后重试')}if(!res.ok)throw new Error(data.error||'操作失败，请重试');return data}
async function refresh(){const data=await api('memories');records=data.items;if($('panel').open)renderPanel()}
async function init(){try{me=await api('me');$('connection').textContent='私人空间 · 已登录';$('banner').textContent='第一版重点：保存目的、线索找回、行动闭环与再次出现。';await refresh()}catch(e){$('connection').textContent='空间尚未连接';$('banner').textContent=e.message}}

function match(r,q){return !q||[r.title,r.text,r.extractedText,r.transcript,r.summary,r.topic,r.clue,r.source,r.place,r.photoPlan,r.scene,r.photoTips,...(r.tags||[]),...(r.links||[])].join(' ').toLowerCase().includes(q.trim().toLowerCase())}
function row(r){const meta=[types[r.kind],r.intent,r.source,r.place,r.status].filter(Boolean).join(' · ');return `<div class="itemrow"><span class="itemicon">${icons[r.kind]||'≡'}</span><button class="rowopen" data-open="${esc(r.id)}"><strong>${esc(r.title)}</strong><p>${esc(meta)}</p></button>${r.deletedAt?`<button class="smallbtn" data-restore="${r.id}">恢复</button>`:`<button class="smallbtn" data-delete="${r.id}" aria-label="删除 ${esc(r.title)}">删除</button>`}</div>`}
function get(id){return records.find(r=>r.id===id)||demo.find(r=>r.id===id)}
async function patch(id,body){const r=await api('memories/'+id,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify(body)});records=records.map(x=>x.id===id?r:x);if($('panel').open)renderPanel();return r}

function openPanel(v){view=v;filter='全部';panelQuery='';renderPanel();show('panel')}
function renderPanel(){
  const names={library:'全部记忆',recall:'凭印象找回',tasks:'等我去做',resurface:'再看一眼',trash:'回收站'};
  $('paneltitle').textContent=names[view]||'记忆';
  const active=records.filter(r=>!r.deletedAt);
  if(view==='recall'){renderRecall(active);return}
  if(view==='tasks'){
    const tasks=active.filter(r=>r.reminder||actionable.has(r.intent));
    $('panelbody').innerHTML='<p class="panelIntro">只有你真正想买、想学、想做或想试的内容，才会来到这里。</p>'+(tasks.length?tasks.map(taskCard).join(''):'<div class="empty"><strong>现在没有等待处理的内容</strong><p>保存时选择“想做”或“想学”，它就会出现在这里。</p></div>');return;
  }
  if(view==='resurface'){
    const chosen=chooseResurface(active);
    const list=chosen.length?chosen:demo;
    $('panelbody').innerHTML='<div class="reviewHead"><span>本次只看 3 条</span><p>不制造新的信息压力，只把值得处理的内容轻轻送回来。</p></div>'+list.slice(0,3).map(r=>resurfaceCard(r)).join('');return;
  }
  const list=records.filter(r=>view==='trash'?!!r.deletedAt:!r.deletedAt).filter(r=>match(r,panelQuery)&&(filter==='全部'||r.kind===filter));
  $('panelbody').innerHTML=(view==='trash'?'<p class="panelIntro">移入这里的资料已从找回和行动中隐藏，可以随时恢复。</p>':`<input class="panelsearch" id="panelSearch" aria-label="搜索资料库" placeholder="输入关键词、地点或备注" value="${esc(panelQuery)}"><div class="filters">${[['全部','全部'],['text','文字'],['image','图片'],['link','链接'],['audio','录音']].map(([v,n])=>`<button class="${filter===v?'active':''}" data-filter="${v}">${n}</button>`).join('')}</div>`)+`<div id="rows">${list.length?list.map(row).join(''):'<div class="empty"><strong>这里还很安静</strong><p>从首页保存第一段记忆，或换个关键词。</p></div>'}</div>`;
  if($('panelSearch'))$('panelSearch').oninput=e=>{panelQuery=e.target.value;const found=records.filter(r=>!r.deletedAt&&match(r,panelQuery)&&(filter==='全部'||r.kind===filter));$('rows').innerHTML=found.map(row).join('')||'<p class="muted">没有匹配内容</p>'};
}

function renderRecall(active){
  $('panelbody').innerHTML=`<p class="panelIntro">不用记得完整内容。把还记得的词、来源和大概时间告诉拾忆。</p><div class="recallBox"><label>还记得哪个词？<input id="recallQuery" placeholder="例如：歌名、栏杆、自他动词"></label><div class="recallGrid"><label>来源<select id="recallSource"><option value="">全部来源</option>${['小红书','微信','直播','游戏','网页','相册','其他'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>保存目的<select id="recallIntent"><option value="">全部目的</option>${visibleIntents.map(x=>`<option>${x}</option>`).join('')}</select></label><label>内容形式<select id="recallKind"><option value="">全部形式</option><option value="image">图片</option><option value="text">文字</option><option value="link">链接</option><option value="audio">录音</option></select></label><label>大概时间<select id="recallTime"><option value="">不限时间</option><option value="7">最近一周</option><option value="30">最近一个月</option><option value="365">今年</option></select></label></div></div><div id="recallResult"></div>`;
  const update=()=>{const q=$('recallQuery').value,source=$('recallSource').value,intent=$('recallIntent').value,kind=$('recallKind').value,days=Number($('recallTime').value||0),cutoff=days?Date.now()-days*86400000:0;const found=active.filter(r=>match(r,q)&&(!source||r.source===source)&&(!intent||r.intent===intent)&&(!kind||r.kind===kind)&&(!cutoff||Date.parse(r.createdAt)>=cutoff));$('recallResult').innerHTML=found.length?`<p class="resultCount">找到 ${found.length} 条可能的记忆</p>`+found.map(row).join(''):'<div class="empty"><strong>换一条线索试试</strong><p>可以只选来源或大概时间，不必填写所有条件。</p></div>'};
  ['recallQuery','recallSource','recallIntent','recallKind','recallTime'].forEach(id=>$(id).addEventListener(id==='recallQuery'?'input':'change',update));update();
}

function chooseResurface(active){return [...active].sort((a,b)=>{const ar=a.reminder&&a.reminder.status!=='已完成'?0:actionable.has(a.intent)?1:2;const br=b.reminder&&b.reminder.status!=='已完成'?0:actionable.has(b.intent)?1:2;return ar-br||Date.parse(a.createdAt)-Date.parse(b.createdAt)}).slice(0,3)}
function taskCard(r){const reminder=r.reminder;return `<article class="task"><div class="cardTop"><span class="intentBadge">${esc(r.intent||'待处理')}</span>${reminder?`<span class="stateBadge">${esc(reminder.status)}</span>`:''}</div><h3>${esc(r.title)}</h3><p>${reminder?`${esc(reminder.when.replace('T',' '))} · ${esc(reminder.priority)}`:'还没有安排时间'}</p><div class="taskActions"><button data-open="${r.id}">查看</button>${reminder&&reminder.status!=='已完成'?`<button data-task="${r.id}" data-status="已完成">完成</button><button data-task="${r.id}" data-status="delay">延后一天</button>`:''}</div></article>`}
function resurfaceCard(r){const image=r.demoImage?`<img src="${r.demoImage}" alt="${esc(r.title)}">`:'';return `<article class="resurfaceCard">${image}<div class="cardTop"><span class="intentBadge">${esc(r.intent)}</span><span>${esc(r.source||types[r.kind])}</span></div><h3>${esc(r.title)}</h3><p>${esc(r.summary||r.text||r.clue||'重新看一眼这段记忆。')}</p><div class="taskActions"><button data-open="${r.id}">打开</button>${r.demo?'<button data-demo-choice="later">下周再看</button>':`<button data-resurface="keep" data-id="${r.id}">继续保留</button>${actionable.has(r.intent)?`<button data-resurface="done" data-id="${r.id}">已经完成</button>`:''}`}</div></article>`}

function openDetail(id){
  const r=get(id);if(!r)return;if(r.deletedAt){notify('请先从回收站恢复这份资料');return}
  const related=(r.demo?demo:records).filter(x=>x.id!==r.id&&!x.deletedAt&&r.topic&&r.topic!=='未分类'&&x.topic===r.topic).slice(0,4);
  const media=r.demoImage?`<img class="media" src="${r.demoImage}" alt="${esc(r.title)}">`:r.hasFile?(r.kind==='image'?`<img class="media" src="/api/memories/${r.id}/file" alt="保存的原始图片">`:`<audio controls src="/api/memories/${r.id}/file"></audio>`):'';
  const recognition=r.scene||r.photoTips?`<div class="recognition"><p class="recognitionLabel">${r.demo?'接入单张识图后的示例输出':'照片内容'}</p>${r.scene?`<strong>画面</strong><p>${esc(r.scene)}</p>`:''}${r.photoTips?`<strong>复刻建议</strong><p>${esc(r.photoTips)}</p>`:''}</div>`:'';
  $('detailbody').innerHTML=`${r.demo?'<p class="demoLabel">演示数据，不会混入你的真实资料</p>':''}${media}<div class="memoryMeta"><span class="intentBadge">${esc(r.intent||'留作参考')}</span>${r.source?`<span>${esc(r.source)}</span>`:''}${r.place?`<span>${esc(r.place)}</span>`:''}</div><label class="field">内容标题<input id="editTitle" maxlength="100" value="${esc(r.title)}" ${r.demo?'disabled':''}></label>${r.summary?`<div class="summary">${esc(r.summary)}</div>`:''}${recognition}<label class="field">原始内容 / 我的说明<textarea id="editText" maxlength="20000" ${r.demo?'disabled':''}>${esc(r.text)}</textarea></label>${(r.links||[]).map((link,i)=>`<div class="linkrow"><a href="${esc(link)}" target="_blank" rel="noopener noreferrer">${esc(link)} ↗</a><button class="smallbtn" data-copy="${i}" data-record="${r.id}">复制</button></div>`).join('')}<div class="detailGrid"><label class="field">记忆线索<input id="editClue" maxlength="120" value="${esc(r.clue||'')}" ${r.demo?'disabled':''}></label><label class="field">来源<input id="editSource" maxlength="60" value="${esc(r.source||'')}" ${r.demo?'disabled':''}></label><label class="field">地点<input id="editPlace" maxlength="100" value="${esc(r.place||'')}" ${r.demo?'disabled':''}></label><label class="field">主题<input id="editTopic" maxlength="60" value="${esc(r.topic||'未分类')}" ${r.demo?'disabled':''}></label></div><label class="field">想怎么复刻 / 下一步<textarea id="editPhotoPlan" maxlength="500" ${r.demo?'disabled':''}>${esc(r.photoPlan||'')}</textarea></label><label class="field">保存目的<select id="editIntent" ${r.demo?'disabled':''}>${visibleIntents.map(m=>`<option ${r.intent===m?'selected':''}>${m}</option>`).join('')}</select></label>${related.length?'<div class="divider"></div><p class="muted">同一主题的记忆</p>'+related.map(x=>`<button class="related" data-open="${x.id}">${esc(x.title)} ↗</button>`).join(''):''}${!r.demo?`<div class="actions"><button data-delete="${r.id}" class="danger">删除</button><button id="saveEdits" class="primary">保存修改</button></div>${r.kind==='image'||r.kind==='audio'?`<div class="divider"></div><p class="capabilityTitle">${r.kind==='image'?'可选：识别这张照片':'可选：转写这段录音'}</p><p class="muted">${r.kind==='image'?'识别画面内容与构图，但地点仍以你填写的信息为准。此功能不是 AI 搜索。':'把录音转成可检索的文字。'}</p><label class="check"><input type="checkbox" id="aiConsent">只将这一份资料发送给识别服务。</label><button id="analyze" class="full" ${!me?.aiEnabled?'disabled':''}>${r.kind==='image'?'识别照片内容':'转写录音'}${!me?.aiEnabled?' · 演示版暂未接入':''}</button>`:''}<button id="newReminder" class="full">安排跟进计划</button><p id="detailError" class="error" role="status"></p>`:'<p class="muted">真实保存时，你可以修改这些信息并安排回访。</p>'}`;
  if(!r.demo){
    $('saveEdits').onclick=async()=>{const b=$('saveEdits');b.disabled=true;try{await patch(id,{title:$('editTitle').value,text:$('editText').value,topic:$('editTopic').value,intent:$('editIntent').value,clue:$('editClue').value,source:$('editSource').value,place:$('editPlace').value,photoPlan:$('editPhotoPlan').value});notify('已保存');openDetail(id)}catch(e){$('detailError').textContent=e.message;b.disabled=false}};
    if($('analyze'))$('analyze').onclick=async()=>{if(!$('aiConsent').checked){$('detailError').textContent='请先确认只发送这一份资料。';return}const b=$('analyze');b.disabled=true;b.textContent='正在处理…';try{await api('memories/'+id+'/analyze',{method:'POST'});await refresh();openDetail(id);notify('识别完成，请核对结果')}catch(e){$('detailError').textContent=e.message;b.disabled=false;b.textContent='重试'}};
    $('newReminder').onclick=()=>reminder(r);
  }
  show('detail');
}

function reminder(r){const now=new Date(Date.now()+86400000);now.setMinutes(now.getMinutes()-now.getTimezoneOffset());$('detailbody').innerHTML=`<h3>${esc(r.title)}</h3><form id="reminderform"><label class="field">重要程度<select id="priority"><option>普通</option><option>重要</option><option>优先处理</option></select></label><label class="field">计划时间<input required id="when" type="datetime-local" value="${now.toISOString().slice(0,16)}"></label><label class="field">跟进频率<select id="frequency"><option>仅一次</option><option>每天</option><option>每周</option></select></label><p class="panelIntro">计划会保存在“等我去做”。演示版暂不发送系统通知。</p><button class="primary full">保存计划</button><p id="reminderError" class="error"></p></form>`;$('reminderform').onsubmit=async e=>{e.preventDefault();if(new Date($('when').value)<=new Date()){$('reminderError').textContent='请选择未来时间';return}try{await patch(r.id,{reminder:{when:$('when').value,priority:$('priority').value,frequency:$('frequency').value,status:'进行中'}});$('detail').close();openPanel('tasks');notify('计划已保存')}catch(err){$('reminderError').textContent=err.message}}}
function deleteRecord(id){const r=get(id);if(!r||r.demo)return;show('confirm');$('confirmDelete').onclick=async()=>{$('confirmDelete').disabled=true;try{await patch(id,{deleted:true});$('confirm').close();$('detail').close();notify('已移到回收站，可随时恢复')}catch(e){notify(e.message)}finally{$('confirmDelete').disabled=false}}}

function switchMode(next){if(recorder?.state==='recording'){notify('先停止录音，再切换输入方式');return}mode=next;document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));$('attachmentArea').hidden=mode==='text';$('recordArea').hidden=mode!=='audio';$('photoFields').hidden=mode!=='image';$('file').accept=mode==='image'?'image/png,image/jpeg,image/webp':'audio/*';$('filelabel').textContent=mode==='image'?'选择图片，或拖到这里':'选择已有录音，也可以直接录制';$('thought').placeholder=mode==='text'?'随手写点什么，也可以粘贴链接…':mode==='image'?'说明这张图是什么、在哪里看到、为什么想留下…':'给这段声音补充一句说明…';$('savehint').textContent=mode==='image'?'先记录你知道的地点和目的；识图可以以后再开。':'保存内容，也保存你当时的目的。';clearAttachment()}
function clearAttachment(){attachment=null;if(attachmentURL)URL.revokeObjectURL(attachmentURL);attachmentURL=null;$('attachmentPreview').innerHTML='';$('file').value=''}
function setAttachment(file){if(file.size>10*1024*1024){notify('文件需小于 10 MB');return}const image=['image/png','image/jpeg','image/webp'].includes(file.type);const audio=/^(audio\/|video\/webm)/.test(file.type);if(!image&&!audio){notify('请选择 PNG、JPG、WebP 图片或音频');return}if(recorder?.state==='recording'){notify('请先停止录音');return}if(mode!==(image?'image':'audio'))switchMode(image?'image':'audio');clearAttachment();attachment=file;attachmentURL=URL.createObjectURL(file);$('attachmentPreview').innerHTML=(image?`<img src="${attachmentURL}" alt="待保存图片">`:`<audio controls src="${attachmentURL}"></audio>`)+`<button id="removeFile" class="smallbtn">移除附件</button>`;$('removeFile').onclick=clearAttachment}

function revisitDate(choice){const d=new Date();if(choice==='今晚')d.setHours(20,0,0,0);if(choice==='三天后')d.setDate(d.getDate()+3);if(choice==='下周')d.setDate(d.getDate()+7);if(choice==='一个月后')d.setMonth(d.getMonth()+1);if(d<=new Date())d.setDate(d.getDate()+1);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)}
async function save(){if(saving)return;if(recorder?.state==='recording'){notify('请先停止录音并试听');return}const text=$('thought').value.trim();if(!text&&!attachment){notify('先写点内容，或添加图片、录音');return}if(!me){openAccount();return}saving=true;$('save').disabled=true;$('save').textContent='保存中…';const form=new FormData(),revisit=$('revisit').value;form.set('text',text);form.set('intent',selectedIntent);form.set('clue',$('clue').value.trim());form.set('source',$('source').value);form.set('place',$('place').value.trim());form.set('photoPlan',$('photoPlan').value.trim());form.set('revisit',revisit);if(revisit!=='不用提醒')form.set('revisitWhen',revisitDate(revisit));if(attachment)form.set('file',attachment);try{const r=await api('memories',{method:'POST',body:form});$('thought').value='';$('clue').value='';$('place').value='';$('photoPlan').value='';$('source').value='';$('revisit').value='不用提醒';clearAttachment();records.unshift(r);notify('已收好：内容、目的和线索都已保存');openDetail(r.id)}catch(e){notify(e.message)}finally{saving=false;$('save').disabled=false;$('save').textContent='收好'}}

async function record(){if(recorder?.state==='recording'){recorder.stop();return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){notify('当前浏览器不支持录音，可以上传已有音频文件');return}try{stream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=['audio/webm','audio/mp4'].find(t=>MediaRecorder.isTypeSupported(t));recorder=new MediaRecorder(stream,mime?{mimeType:mime}:{});const parts=[];let seconds=0;recorder.ondataavailable=e=>{if(e.data.size)parts.push(e.data)};recorder.onstop=()=>{clearTimeout(recordTimer);clearInterval(recordClock);stream.getTracks().forEach(t=>t.stop());const type=recorder.mimeType;const file=new File(parts,'录音.'+(type.includes('mp4')?'m4a':'webm'),{type});recorder=null;$('record').textContent='● 重新录音';$('recordState').textContent='录音已停止，可试听后保存';setAttachment(file)};recorder.start();$('record').textContent='■ 停止录音';$('recordState').textContent='正在录音 0:00';recordClock=setInterval(()=>{seconds++;$('recordState').textContent=`正在录音 ${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`},1000);recordTimer=setTimeout(()=>{if(recorder?.state==='recording')recorder.stop()},120000)}catch{stream?.getTracks().forEach(t=>t.stop());notify('未获得麦克风权限，可以上传已有录音')}}

function openAccount(){$('accountbody').innerHTML=`<div class="accountcard"><b>${me?'已登录 · 私人空间':'登录 / 首次使用'}</b><p>${me?esc(me.email):'首次通过 ChatGPT 登录后，即可使用账号空间。'}</p>${me?'<a href="/signout-with-chatgpt?return_to=%2F" target="_top">退出登录</a>':'<a class="signin" href="/signin-with-chatgpt?return_to=%2F" target="_top">使用 ChatGPT 登录</a>'}<p>文字、图片与行动计划按账号隔离保存。</p></div><div class="accountcard"><b>关键词找回 · 不使用 AI</b><p>根据你填写的记忆词、来源、地点、目的与时间组合筛选，不产生模型费用。</p></div><div class="accountcard"><b>单张照片识别 · ${me?.aiEnabled?'可以使用':'演示版暂未接入'}</b><p>可以描述画面中的景物、文字和构图，并给出复刻拍摄建议；无法只凭普通风景照保证认出准确地点，因此地点以你填写的内容为准。</p><p>它与 AI 搜索相互独立，只在你打开某一张照片并主动确认后处理这一张。</p></div><div class="accountcard"><b>数据可带走</b><p>删除先进入回收站。你也可以导出全部文字信息与链接。</p><button id="export" ${!me?'disabled':''}>导出文字资料</button></div>`;if($('export'))$('export').onclick=()=>{const blob=new Blob([JSON.stringify(records,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='拾忆-文字资料.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);notify('文字资料已导出')};show('accountDialog')}

document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.view)openPanel(b.dataset.view);if(b.dataset.close)$(b.dataset.close).close();if(b.dataset.open)openDetail(b.dataset.open);if(b.dataset.delete)deleteRecord(b.dataset.delete);if(b.dataset.restore){await patch(b.dataset.restore,{deleted:false});notify('已恢复资料')}if(b.dataset.mode)switchMode(b.dataset.mode);if(b.dataset.intent){selectedIntent=b.dataset.intent;document.querySelectorAll('[data-intent]').forEach(x=>x.classList.toggle('active',x.dataset.intent===selectedIntent))}if(b.dataset.filter){filter=b.dataset.filter;renderPanel()}if('copy' in b.dataset){await navigator.clipboard.writeText(get(b.dataset.record).links[Number(b.dataset.copy)]);notify('链接已复制')}if(b.dataset.task){const r=get(b.dataset.task);let rem={...r.reminder};if(b.dataset.status==='delay'){const d=new Date(rem.when);d.setDate(d.getDate()+1);d.setMinutes(d.getMinutes()-d.getTimezoneOffset());rem.when=d.toISOString().slice(0,16)}else rem.status=b.dataset.status;await patch(r.id,{reminder:rem});notify('行动状态已更新')}if(b.dataset.resurface==='done'){const r=get(b.dataset.id);await patch(r.id,{lifeStatus:'已完成',reminder:r.reminder?{...r.reminder,status:'已完成'}:null});notify('太好了，已经完成')}if(b.dataset.resurface==='keep')notify('继续为你保留');if(b.dataset.demoChoice)notify('演示：它会在下周再次出现');if('focusCapture' in b.dataset){document.querySelectorAll('dialog[open]').forEach(d=>d.close());$('composer').scrollIntoView({behavior:'smooth',block:'center'});$('thought').focus()}}catch(err){notify(err.message)}});

$('save').onclick=save;$('file').onchange=e=>{if(e.target.files[0])setAttachment(e.target.files[0])};$('filepick').ondragover=e=>e.preventDefault();$('filepick').ondrop=e=>{e.preventDefault();if(e.dataTransfer.files[0])setAttachment(e.dataTransfer.files[0])};$('thought').onpaste=e=>{if(e.clipboardData.files.length){e.preventDefault();setAttachment(e.clipboardData.files[0])}};$('record').onclick=record;$('account').onclick=openAccount;$('aboutPhoto').onclick=openAccount;$('openScenicDemo').onclick=()=>openDetail('demo-scenic');$('home').onclick=()=>{document.querySelectorAll('dialog[open]').forEach(d=>d.close());$('composer').scrollIntoView({behavior:'smooth',block:'start'})};document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openPanel('recall');setTimeout(()=>$('recallQuery')?.focus(),0)}});window.addEventListener('pagehide',()=>{stream?.getTracks().forEach(t=>t.stop());clearTimeout(recordTimer);clearInterval(recordClock)});init();

if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'find_saved_memory',description:'Find saved memories using exact keywords and user-provided context such as source, place, intent, and notes. Does not call AI.',inputSchema:{type:'object',properties:{query:{type:'string'}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(typeof input?.query!=='string')throw new Error('query must be a string');openPanel('recall');setTimeout(()=>{if($('recallQuery')){$('recallQuery').value=input.query;$('recallQuery').dispatchEvent(new Event('input'))}},0);return{items:records.filter(r=>!r.deletedAt&&match(r,input.query)).map(r=>({id:r.id,title:r.title}))}}})).catch(()=>{})}catch{}}
